<?php

namespace ContainerZAIMtKk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RegistrationController' shared autowired service.
     *
     * @return \App\Controller\RegistrationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RegistrationController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/UserService.php';

        $a = ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService'));

        $container->services['App\\Controller\\RegistrationController'] = $instance = new \App\Controller\RegistrationController(($container->privates['security.authentication.guard_handler'] ?? $container->load('getSecurity_Authentication_GuardHandlerService')), new \App\Services\UserService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')), ($container->privates['App\\Repository\\UserForgottenPasswordRepository'] ?? $container->load('getUserForgottenPasswordRepositoryService')), $a), $a);

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\RegistrationController', $container));

        return $instance;
    }
}
